# Generated by Django 5.1.1 on 2024-09-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThuVien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='totalBorrowCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='thich',
            unique_together={('user', 'sach')},
        ),
    ]
