# Generated by Django 5.1.1 on 2024-10-17 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThuVien', '0002_sach_totalborrowcount_alter_thich_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietphieumuon',
            name='sach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chi_tiet_phieu_muon', to='ThuVien.sach'),
        ),
        migrations.AlterField(
            model_name='phieumuon',
            name='docGia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
