# Generated by Django 5.1.1 on 2024-10-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThuVien', '0004_sach_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='nam_sinh',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
