# Generated by Django 5.1.1 on 2024-10-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThuVien', '0004_chitietphieumuon_datratienphat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietphieumuon',
            name='tinhTrang',
            field=models.CharField(choices=[('borrowed', 'Đang mượn'), ('returned', 'Đã trả'), ('late', 'Trễ hạn'), ('paid', 'Đã trả phạt')], default='borrowed', max_length=10),
        ),
    ]
